
<form class="" action="<?php echo $block->getBaseUrl().'test/index/save'; ?>" id="vky-test-form" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span>Customer Registration Form</span></legend><br>
        <div class="field title">
            <label class="label" for="title"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span>Contact</span></label>
            <div class="control">
                <input name="contact" id="contact" title="Contact" value="" class="input-text" type="text">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>